load: ${reward_load}
load_iteration: ${reward_load_iteration}
use_distributed_optimizer: True

num_layers: ${reward_num_layers}
hidden_size: ${reward_hidden_size}
num_attention_heads: ${reward_num_attention_heads}
ffn_hidden_size: ${reward_ffn_hidden_size}
tensor_model_parallel_size: ${reward_tp:4}

save_inference: True
save_inference_interval: 10