includes:
  - base_train.yaml
  - policy_shared.yaml


load: ${policy_load:/cpfs01/shared/Group-m6/xianyan.xianyanjia/llama/megatron_models/vicuna-13b-new-tp8-pp2/}

bf16: True
use_checkpoint_opt_param_scheduler: False
adam_beta1: 0.9
adam_beta2: 0.95
num_workers: 8
init_method_std: 0.006

recompute_granularity: selective
# recompute_method: uniform
# recompute_granularity: full
sequence_parallel: True

log_num_zeros_in_grad: True
no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True
dummy: 0


lr_decay_iters: 12000
lr_warmup_iters: 100
lr: ${policy_lr:0.00000008}
min_lr: 0.000000001
lr_decay_style: ${policy_lr_decay_style:linear}
weight_decay: 0.01