includes:
        - base.yaml

temperature: 1.0
seed: 42
no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True
log_num_zeros_in_grad: True
attention_dropout: 0.0
hidden_dropout: 0.0
retro_encoder_attention_dropout: 0.0
retro_encoder_hidden_dropout: 0.0
inference_batch_times_seqlen_threshold: ${inference_batch_times_seqlen_threshold:4096}
