includes:
        - base_inference.yaml
        - policy_shared.yaml


top_p: ${policy_top_p:0.9}
top_k: ${policy_top_k:0}

eval_temperature: 0.01
eval_top_k: 1
eval_top_p: 0


pipeline_model_parallel_size: ${policy_pp:1}
