includes:
        - base_train.yaml
        - reward_shared.yaml

pipeline_model_parallel_size: ${ppo_value_pp}

lr_decay_iters: 4000
lr_warmup_iters: 80
lr: 0.000005
min_lr: 0.000001
lr_decay_style: constant
weight_decay: 0.01

use_checkpoint_opt_param_scheduler: False
adam_beta1: 0.9
adam_beta2: 0.95
num_workers: 8
init_method_std: 0.006

sequence_parallel: True

no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True


recompute_activations: ${value_recompute_activations:False}
recompute_granularity: ${value_recompute_granularity:None}
