includes:
        - base_inference.yaml
        - policy_shared.yaml

parallel_output: True
pipeline_model_parallel_size: ${ref_pp:1}
inference_batch_times_seqlen_threshold: ${inference_batch_times_seqlen_threshold:16384}
