FROM nvcr.io/nvidia/pytorch:24.12-py3
RUN unset NCCL_DEBUG
ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
ENV PIP_TRUSTED_HOST=mirrors.aliyun.com

RUN pip install --no-cache-dir -U \
    vllm==0.8.5.post1 \
    wandb==0.19.3 \
    transformers==4.51.3 \
    modelscope==1.26.0 \
    datasets==3.6.0 \
    deepspeed==0.16.7 \
    grpcio==1.70.0 \
    nvidia-modelopt==0.27.0 \
    nvidia-modelopt-core==0.27.0 \
    ray[default]==2.46.0

RUN pip install --no-cache-dir -U setuptools==69.5.1
RUN pip install --no-cache-dir hydra-core==1.3.2

RUN pip uninstall -y flash_attn && pip install https://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/csrc/flash-attention/torch2.6.0-cu12x/flash_attn-2.4.2-cp312-cp312-linux_x86_64.whl --no-cache-dir
RUN pip uninstall -y apex && pip install https://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/csrc/apex/torch2.6.0-cuda12x/apex-0.1-cp312-cp312-linux_x86_64.whl --no-cache-dir
RUN pip uninstall -y transformer_engine && pip install https://pai-vision-data-hz.oss-cn-zhangjiakou.aliyuncs.com/csrc/transformer_engine/torch2.6.0-cuda12x/transformer_engine-1.13.0%2Be5edd6c-cp312-cp312-linux_x86_64.whl --no-cache-dir