load: ${policy_inference_load}
load_iteration: ${policy_load_iteration}
num_layers: ${policy_num_layers}
hidden_size: ${policy_hidden_size}
num_attention_heads: ${policy_num_attention_heads}
ffn_hidden_size: ${policy_ffn_hidden_size}
num_experts: ${policy_num_experts}
moe_router_topk: ${policy_moe_router_topk}
tensor_model_parallel_size: ${policy_tp:1}
expert_model_parallel_size: ${policy_ep:8}
group_query_attention: ${group_query_attention:True}
num_query_groups: ${policy_num_query_groups}
use_distributed_optimizer: True

