includes:
  - base_train.yaml
  - policy_shared.yaml


bf16: True
use_checkpoint_opt_param_scheduler: False
adam_beta1: 0.9
adam_beta2: 0.95
num_workers: 8
init_method_std: 0.006

# dropout
attention_dropout: ${attention_dropout:0.1}
hidden_dropout: ${hidden_dropout:0.1}
retro_encoder_hidden_dropout: ${retro_encoder_hidden_dropout:0.1}
retro_encoder_attention_dropout: ${retro_encoder_attention_dropout:0.1}

recompute_granularity: selective

log_num_zeros_in_grad: True
no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True


lr_decay_iters: 12000
lr_warmup_iters: 100
lr: ${policy_lr:2.4e-7}
min_lr: ${policy_min_lr:1e-9}
lr_decay_style: ${policy_lr_decay_style:linear}
weight_decay: 0.01
pipeline_model_parallel_size: ${ppo_policy_pp:1}
sequence_parallel: ${sequence_parallel:True}

recompute_activations: ${policy_recompute_activations:False}
recompute_granularity: ${policy_recompute_granularity:None}
