includes:
  - base_train.yaml
  - policy_shared.yaml


# load: ${policy_load:/mnt/shared/Group-m6/xianyan.xianyanjia/checkpoint/13b.new1.data-v10.15.5-13B-bf16-mp4-pp1-lr-1e-5-minlr-1e-6-bs-128-gpus-64-seqlen-8192-tp8-pp2}

use_checkpoint_opt_param_scheduler: False
adam_beta1: 0.9
adam_beta2: 0.95
num_workers: 8
init_method_std: 0.006

recompute_granularity: selective
# recompute_method: uniform
# recompute_granularity: full
sequence_parallel: True

log_num_zeros_in_grad: True
no_load_optim: True
no_load_rng: True
no_load_args: True
no_load_scheduler: True
dummy: 0


lr_decay_iters: 12000
lr_warmup_iters: 100
lr: ${policy_lr:0.00000008}
min_lr: 0.000000001
lr_decay_style: ${policy_lr_decay_style:linear}
weight_decay: 0.01