includes:
  - base.yaml
zero_stage: 3
pretrain_or_model: ${model_path}
bf16: True
max_samples: 80000
seed: 8888
prompt_max_len: 1024

reward_data: ${reward_dataset_path}
reward_data_probs: 0.8,0.2
max_len: 1024
input_template: "\n\nHuman: {}\n\nAssistant:"
chosen_key: chosen
rejected_key: rejected
prompt_key: messages
apply_chat_template: True
