includes:
        - base_inference.yaml
        - reward_shared.yaml

tokenizer_type: GPT2BPETokenizer
reward_bias: 0

save_inference: False
save_inference_interval: 100
pipeline_model_parallel_size: ${reward_pp:1}
